### ISSUE TITLE
Reflected XSS in Twitter Generic Error

### ISSUE THREAD

**Issue by exdeejay** [soatok/faq-off#19]
## Bug

A reflected XSS is present in the generic error handler. It seems that the error parameter is not sanitized before being inserted into the webpage.

## Steps to reproduce:

1. go to /generic-error/twitter-error?error=<script>alert(1)</script>
2. view alert box showing execution of javascript code

**Comment by soatok** [comment]
https://github.com/soatok/faq-off/commit/4d4f11083fe7f7d9fddc5b1fa7567a9dde3da6d6

**Comment by soatok** [comment]
Thanks for reporting this! You can verify it's fixed [here](https://faq.dhol.es/generic-error/twitter-error?error=%3Cscript%3Ealet(1)%3C/script%3E).
